### ISSUE TITLE
hello, could you help where is the res/pvt_v2_b2.pth ? 

### ISSUE THREAD

**Issue by plsuarez** [xinyang920/OAFormer#2]
It is used in train.py program: net.load_state_dict(torch.load("res/pvt_v2_b2.pth"), strict=False)

**Comment by xinyang920** [comment]
https://drive.google.com/file/d/1snw4TYUCD5z4d3aaId1iBdw-yUKjRmPC/view?usp=sharing

**Comment by plsuarez** [comment]
Thanks.
Can you help me with the directory structure of your dataset for training and testing? and an example of the Txt files needed to read the image files. And maybe you can help me with a copy or tell us what dataset you trained, tested and validated your model on?
thanks in advance
